CREATE TABLE IF NOT EXISTS addresses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street TEXT NOT NULL,
    city TEXT NOT NULL,
    state TEXT NOT NULL,
    postal_code TEXT NOT NULL,
    country TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS library_cards (
    barcode TEXT PRIMARY KEY,
    issued_on DATE NOT NULL,
    status TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS accounts (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    phone TEXT,
    password TEXT NOT NULL,
    card_barcode TEXT NOT NULL REFERENCES library_cards(barcode) ON UPDATE CASCADE,
    status TEXT NOT NULL,
    outstanding_fine DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS authors (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS books (
    isbn TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    subject TEXT NOT NULL,
    publisher TEXT NOT NULL,
    publication_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS book_authors (
    book_isbn TEXT NOT NULL REFERENCES books(isbn) ON DELETE CASCADE ON UPDATE CASCADE,
    author_id TEXT NOT NULL REFERENCES authors(id) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (book_isbn, author_id)
);

CREATE TABLE IF NOT EXISTS racks (
    rack_number TEXT PRIMARY KEY,
    location_identifier TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS book_items (
    barcode TEXT PRIMARY KEY,
    book_isbn TEXT NOT NULL REFERENCES books(isbn) ON DELETE CASCADE ON UPDATE CASCADE,
    rack_number TEXT REFERENCES racks(rack_number) ON UPDATE CASCADE,
    status TEXT NOT NULL,
    due_date DATE,
    format TEXT NOT NULL,
    is_reference_only BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS book_lendings (
    id TEXT PRIMARY KEY,
    book_item_barcode TEXT NOT NULL REFERENCES book_items(barcode) ON UPDATE CASCADE,
    member_id TEXT NOT NULL REFERENCES accounts(id) ON UPDATE CASCADE,
    checkout_date DATE NOT NULL,
    due_date DATE NOT NULL,
    return_date DATE
);

CREATE TABLE IF NOT EXISTS book_reservations (
    id TEXT PRIMARY KEY,
    book_isbn TEXT NOT NULL REFERENCES books(isbn) ON UPDATE CASCADE,
    member_id TEXT NOT NULL REFERENCES accounts(id) ON UPDATE CASCADE,
    created_on DATE NOT NULL,
    status TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS fines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE ON UPDATE CASCADE,
    book_title TEXT NOT NULL,
    late_days BIGINT NOT NULL,
    amount DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS book_reviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_isbn TEXT NOT NULL REFERENCES books(isbn) ON DELETE CASCADE ON UPDATE CASCADE,
    member_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE ON UPDATE CASCADE,
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment TEXT,
    created_at TEXT NOT NULL,
    UNIQUE (book_isbn, member_id)
);

CREATE INDEX IF NOT EXISTS idx_accounts_type ON accounts(type);
CREATE INDEX IF NOT EXISTS idx_book_items_book_isbn ON book_items(book_isbn);
CREATE INDEX IF NOT EXISTS idx_book_lendings_member_id ON book_lendings(member_id);
CREATE INDEX IF NOT EXISTS idx_book_lendings_item ON book_lendings(book_item_barcode);
CREATE INDEX IF NOT EXISTS idx_book_reservations_member_id ON book_reservations(member_id);
CREATE INDEX IF NOT EXISTS idx_book_reservations_book_isbn ON book_reservations(book_isbn);
CREATE INDEX IF NOT EXISTS idx_notifications_recipient ON notifications(recipient);
